In [ ]:
pip install --upgrade pyswarm

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

# Load the Auto MPG dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']
data = pd.read_csv(url, delim_whitespace=True, names=column_names)

print(data.head())


C:\Users\rmx\AppData\Local\Temp\ipykernel_21556\267469941.py:11: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(url, delim_whitespace=True, names=column_names)


    mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                   car_name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  


In [3]:
# Preprocess the data
data = data.replace('?', np.nan)  # Replace missing values marked as '?'
data = data.dropna()  # Drop rows with missing values
data['horsepower'] = pd.to_numeric(data['horsepower'])  # Convert horsepower to numeric
data = data.drop(columns=['car_name','origin','model_year'])  # Drop the irrelevant variables

print(data.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration
0  18.0          8         307.0       130.0  3504.0          12.0
1  15.0          8         350.0       165.0  3693.0          11.5
2  18.0          8         318.0       150.0  3436.0          11.0
3  16.0          8         304.0       150.0  3433.0          12.0
4  17.0          8         302.0       140.0  3449.0          10.5


In [5]:
# Split into features and target
X1 = data.drop(columns=['acceleration'])  # Features
y = data['acceleration']  # Target

In [7]:
# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# Define and train the neural network
model = MLPRegressor(hidden_layer_sizes=(64, 32), activation='relu', solver='adam', max_iter=100000, random_state=42)
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Example predictions
print(f"Example Predictions: {y_pred[:5]}")

Mean Squared Error: 2.535989036321592
Example Predictions: [17.24444908 13.65421722 16.54270254 15.86423045 17.57148226]


In [8]:
X_test[:5]

array([[ 0.32765448, -0.86401356, -0.94164742, -0.92267201, -0.92958509],
       [-0.23680661, -0.86401356, -0.70243687,  0.27393484, -0.21523071],
       [ 1.62334924, -0.86401356, -0.98948953, -1.15679075, -1.38813931],
       [ 0.32765448, -0.86401356, -0.98948953, -0.89665882, -1.20542491],
       [ 0.45594109, -0.86401356, -0.52063686, -0.48044774, -0.22112473]])

In [9]:
df=pd.DataFrame(X).describe()
df.min

<bound method DataFrame.min of                   0             1             2             3             4
count  3.920000e+02  3.920000e+02  3.920000e+02  3.920000e+02  3.920000e+02
mean   1.450087e-16 -1.087565e-16 -7.250436e-17 -1.812609e-16 -1.812609e-17
std    1.001278e+00  1.001278e+00  1.001278e+00  1.001278e+00  1.001278e+00
min   -1.853218e+00 -1.451004e+00 -1.209563e+00 -1.520975e+00 -1.608575e+00
25%   -8.269250e-01 -8.640136e-01 -8.555316e-01 -7.665929e-01 -8.868535e-01
50%   -8.927701e-02 -8.640136e-01 -4.153842e-01 -2.853488e-01 -2.052109e-01
75%    7.125143e-01  1.483947e+00  7.782764e-01  5.600800e-01  7.510927e-01
max    2.970359e+00  1.483947e+00  2.493416e+00  3.265452e+00  2.549061e+00>

In [8]:
min_values = np.min(X, axis=0)
max_values = np.max(X, axis=0)
print(min_values)

[-1.8532179  -1.4510037  -1.20956322 -1.52097544 -1.6085754 ]


In [27]:
help(pso)

Help on function pso in module pyswarm.pso:

pso(func, lb, ub, ieqcons=[], f_ieqcons=None, args=(), kwargs={}, swarmsize=100, omega=0.5, phip=0.5, phig=0.5, maxiter=100, minstep=1e-08, minfunc=1e-08, debug=False)
    Perform a particle swarm optimization (PSO)

    Parameters
    func : function
        The function to be minimized
    lb : array
        The lower bounds of the design variable(s)
    ub : array
        The upper bounds of the design variable(s)

    Optional
    ieqcons : list
        A list of functions of length n such that ieqcons[j](x,*args) >= 0.0 in
        a successfully optimized problem (Default: [])
    f_ieqcons : function
        Returns a 1-D array in which each element must be greater or equal
        to 0.0 in a successfully optimized problem. If f_ieqcons is specified,
        ieqcons is ignored (Default: None)
    args : tuple
        Additional arguments passed to objective and constraint functions
        (Default: empty tuple)
    kwargs : dict
    

In [11]:
model.predict(max_values.reshape(1, -1))

array([19.37251315])

In [17]:
from pyswarm import pso

def objective_function(x):
    return model.predict(x.reshape(1, -1))

lb = min_values
ub = max_values

best_pos, best_cost = pso(objective_function, lb, ub, swarmsize=1000, maxiter =1000)
print(best_pos)
print(scaler.inverse_transform(best_pos.reshape(1, -1)))
print(model.predict(best_pos.reshape(1, -1)))
print(best_cost)

Stopping search: Swarm best objective change less than 1e-08
[-0.08823872  1.33523015  0.64249831  1.419391   -1.04528405]
[[  22.75809347    7.74664503  261.55977348  159.033663   2090.85043934]]
[6.271794]
[6.271794]


In [34]:
np.set_printoptions(suppress=True)
print(best_pos)
print(scaler.inverse_transform(best_pos.reshape(1, -1)))
print(model.predict(best_pos.reshape(1, -1)))
print(best_cost)

[ 1.87692376 -1.4510037   0.41102161  0.84255898 -1.16154685]
[[  38.076625      3.          237.36804043  136.85906782 1992.22256809]]
[6.69590064]
[6.69590064]


In [ ]:
scaler.inverse_transform(X)

In [ ]:
X

In [ ]:
fopt

In [ ]:
pso(banana, lb, ub, f_ieqcons=con)

In [ ]:
def banana(x):
    x1 = x[0]
    y1 = x[1]
    return +(-x1 - 2*y1)

def con(x):
    x1 = x[0]
    print("con:x1 ", x1)
    y1 = x[1]
    print("con:y1 ", y1)
    return -2*x1 - y1 +20

lb = [0, 0]
ub = [1000, 40]

pso(banana, lb=lb, ub=ub, ieqcons=[con], maxiter=100, debug = True, 
          swarmsize=100, omega=5, phip=1000, phig=5)


(array([29.48385313, 14.80213391]), 1e+100)

In [ ]:
xopt

In [ ]:
fopt